items() for iteritems()
iteritems() does not exist at all in [python 3.4](https://docs.python.org/3/library/stdtypes.html#dict-views) - items() looks to do the job as the iter(kwargs) raise a ValueError : 
```python 
    (k, v) for k, v in iter(kwargs)
ValueError: too many values to unpack (expected 2)
```